{
 "title": "Wago / Heizung",
 "time": { "from": "now-30d", "to": "now" },
 "refresh": "auto",
 "panels": [
  {
   "title": "Total Power in W",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "kwatt" } },
   "targets": [
    { "expr": "wago_power_total_kw{}", "legendFormat": "Total power in W" },
    { "expr": "wago_power_L1_kw{}", "legendFormat": "L1 power in W" },
    { "expr": "wago_power_L2_kw{}", "legendFormat": "L2 power in W" },
    { "expr": "wago_power_L3_kw{}", "legendFormat": "L3 power in W" }
   ]
  },
  {
   "title": "Total Energy kWh",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 0 },
   "targets": [
    { "expr": "wago_energy_total_kwh", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "L1/L2/L3 Energy kW/h per hour",
   "type": "barchart",
   "gridPos": { "h": 16, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "targets": [
    {
     "expr": "increase(wago_energy_L1_kwh[1d])",
     "legendFormat": "L1 kWh"
    },
    {
     "expr": "increase(wago_energy_L2_kwh[1d])",
     "legendFormat": "L2 kWh"
    },
    {
     "expr": "increase(wago_energy_L3_kwh[1d])",
     "legendFormat": "L3 kWh"
    }
   ]
  },
  {
   "title": "kWh/d",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 11 },
   "targets": [
    {
     "expr": "increase(wago_energy_total_kwh[1d])",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}