{
 "title": "Heat Pump Energy Monitor (Desktop)",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "Temperatur Innen",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 10, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "avg_over_time(sensor_temperature_celsius{sensor_name=\"temp_indoor\"}[5m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Innen C°",
   "type": "stat",
   "gridPos": { "h": 7, "w": 2, "x": 10, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sensor_temperature_celsius{sensor_name=\"temp_indoor\"}"
    }
   ]
  },
  {
   "title": "Zählerstand Heizung",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 10, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "targets": [
    {
     "expr": "avg_over_time(wago_energy_total_kwh[1m])",
     "legendFormat": "Total Energy"
    }
   ]
  },
  {
   "title": "Leistung",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 22, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "wago_power_total_kw * 1000" }
   ]
  },
  {
   "title": "Leistungsaufnahme (Verlauf) Heizung",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 10, "x": 12, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "expr": "avg_over_time(wago_power_total_kw[1m]) * 1000",
     "legendFormat": "Total Power"
    },
    { "expr": "wago_power_L1_kw * 1000", "legendFormat": "L1 Power" },
    { "expr": "wago_power_L2_kw * 1000", "legendFormat": "L2 Power" },
    { "expr": "wago_power_L3_kw * 1000", "legendFormat": "L3 Power" }
   ]
  },
  {
   "title": "Pumpe",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 22, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "bool_on_off" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "thermostat_switch_state{}", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Temperatur Aussen",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 10, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "avg_over_time(sensor_temperature_celsius{sensor_name=\"temp_outdoor\"}[5m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Aussen C°",
   "type": "stat",
   "gridPos": { "h": 7, "w": 2, "x": 10, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sensor_temperature_celsius{sensor_name=\"temp_outdoor\"}"
    }
   ]
  },
  {
   "title": "Flow Rate",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 22, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "flowlpm" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "heatpump_flow_rate_lpm", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Pufferspeicher (oben)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 10, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "avg_over_time(sensor_temperature_celsius{sensor_name=\"temp_buffer\"}[5m])+2.5",
     "legendFormat": "__auto"
    },
    {
     "expr": "heatpump_flow_temperature_celsius",
     "legendFormat": "{{Vorlauf}}"
    },
    {
     "expr": "heatpump_return_temperature_celsius",
     "legendFormat": "{{Ruecklauf}}"
    }
   ]
  },
  {
   "title": "Puffer C°",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 4, "x": 10, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sensor_temperature_celsius{sensor_name=\"temp_buffer\"}+2.5"
    }
   ]
  },
  {
   "title": "Verbrauch seit 09/2025",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 14, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "wago_energy_total_kwh - 60" }
   ]
  },
  {
   "title": "Zählerstand Total",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "wago_energy_total_kwh" }
   ]
  }
 ]
}